### ISSUE TITLE
python lastfm-artists_by_genre_pylast.py not recognising config.ini?

### ISSUE THREAD

**Issue by mckenna654** [dbeley/lastfm-scripts#20]
Hi,

I've downloaded the full directory from your github and configured the config.ini as per the sample file.

I receiving the below error when trying to run python lastfm-artists_by_genre_pylast.py. The config.ini file is in the same directory.

```
PS C:\Users\jake> python C:\Users\jake\Desktop\lastfm-scraper-master\lastfm-artists_by_genre_pylast.py -g "Hardcore Punk"
Traceback (most recent call last):
  File "C:\Users\jake\Desktop\lastfm-scraper-master\lastfm-artists_by_genre_pylast.py", line 80, in <module>
    main()
  File "C:\Users\jake\Desktop\lastfm-scraper-master\lastfm-artists_by_genre_pylast.py", line 38, in main
    network = lastfmconnect()
  File "C:\Users\jake\Desktop\lastfm-scraper-master\lastfm-artists_by_genre_pylast.py", line 16, in lastfmconnect
    api_key = config["lastfm"]["api_key"]
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\configparser.py", line 965, in __getitem__
    raise KeyError(key)
KeyError: 'lastfm'
PS C:\Users\jake>
```

Any assistance would be appreciated!

**Comment by mckenna654** [comment]
resolved by setting the exact path for config.read, now getting

```
PS C:\Users\jake> python C:\Users\jake\Desktop\lastfm-scraper-master\lastfm-artists_by_genre_pylast.py -g "Hardcore Punk"
INFO:pylast:auth.getMobileSession
INFO:httpx:HTTP Request: POST https://ws.audioscrobbler.com/2.0/?username=xInhaleExhalex "HTTP/1.1 200 OK"
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]INFO:pylast:tag.getTopArtists
INFO:httpx:HTTP Request: POST https://ws.audioscrobbler.com/2.0/ "HTTP/1.1 200 OK"
ERROR:root:'charmap' codec can't encode characters in position 0-3: character maps to <undefined>
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.81it/s]
INFO:root:Runtime : 0.90 seconds
PS C:\Users\jake>

```
